### ISSUE TITLE
Cross compile magic-wormhole.rs into wasm and try it with minimal web client

### ISSUE THREAD

**Issue by vu3rdd** [LeastAuthority/winden#122]
Cross compile [magic-wormhole.rs](https://github.com/LeastAuthority/magic-wormhole.rs) into Wasm and try it with [minimal web client](https://github.com/LeastAuthority/wormhole-william-minimal-client).

**Objective**: Confirm, that rust library can work under WASM in Web Client without much additional development effort.

**Secondary objective**: Understand how much effort requires if we want to switch Winden from Go to Rust library.

**Comment by piegamesde** [comment]
`cargo build --target wasm32-unknown-unknown --no-default-features --package magic-wormhole --features transit --features transfer` works for me on the `wasm` branch. I'll try to rebase it onto `master` and see if it still works.

**Comment by piegamesde** [comment]
I don't know web stuff either, but you can just stub the JS bindings on the Rust and I'll fill in the implementation glue code.

Also rebasing/merging is a bit tricky because the code base has somewhat changed since. I propose cherry-picking and rewriting the relevant changes instead (the diff is not that large, mostly sprinkling in `cfg` attributes here and there). Also, the current code on the `wasm` branch will use WebSocket connections instead of TCP if and only if compiling for a WebAssembly target. We might want to discuss implementing first-class WebSocket support first. (Personally I don't see the point in using when it's not required, but I've seen people with different opinions on that)

**Comment by meejah** [comment]
+1 on websockets "only if necessary" (or asked I guess -- e.g. might be a fun command-line option for testing, debugging). If "masking" gets turned on there can be a ton of overhead (XOR on the entire stream) and in any case it's a lot more complex than TCP.

**Comment by piegamesde** [comment]
The major upside of WS even on the desktop is that it's guaranteed to be hassle free with (stupidly) restrictive firewalls. The biggest downside IMO is the lack of any possibility for a direct connection.

**Comment by meejah** [comment]
> The major upside of WS even on the desktop is that it's guaranteed to be hassle free even with (stupidly) restrictive firewalls. The biggest downside IMO is the lack of any possibility for a direct connection.

I don't think either of those things are true (maybe "sometimes" the first one).

To determine if a given stream is WS or "just TCP" you'd have to do DPI (deep packet inspection) -- do desktop firewalls _do_ that? How would they do this on TLS streams? (Some weird corporate firewalls that MitM all TLS connections can, of course, but ...)

You absolutely can have a direct WebSocket connection -- just not from inside a browser.

**Comment by JustusFT** [comment]
Since Winden already switched to Rust (https://github.com/LeastAuthority/winden/pull/141), we can close this now
