### ISSUE TITLE
Code clean, get rid of Vue dependencies

### ISSUE THREAD

**Issue by donpui** [LeastAuthority/winden#85]
With refactoring original repo: https://github.com/LeastAuthority/Transfer and moving to ReactJS, we still have some dependencies on Vue. It would be good to get rid of that and have more cleaner packages and code.

**Comment by JustusFT** [comment]
Some information why the vue dependencies are still around:

When migrating from vue to react, the dependencies were to be kept until we no longer had any code that depends on it.
However in the end it still affects the application even after removing all vue related code. If `@ionic/vue` is not imported for it's side effects [(like this)](https://github.com/LeastAuthority/winden/blob/b6bf87f5ec1d616df74af457152dc3829eb11743/client/src/app/index.tsx#L1), file download progress shows in the browser's built in download manager alongside the webapp's own download progress screen

It might not seem like a problem at first but this gives the user the option to cancel the download outside the app and through the browser's built in download manager instead. If the user cancels the download, the transfer will keep going even though the receiver is not writing the file anywhere anymore. I tried adding a cancel download event to handle this, but it only works on chrome.
So either one of the following options should to be done in order to remove vue deps:
- disable the browser's download manager without importing `@ionic/vue`
- add cancellation detection for when the user cancels through the browser's download manager. It must work on all browsers
