### ISSUE TITLE
Winden fails to download file sent from Destiny

### ISSUE THREAD

**Issue by btlogy** [LeastAuthority/winden#95]
## What happened?

I've tried to send a file from my Android device and my laptop browser via https://winden.app/ and got this reproducible error:
```
Oops - Unfortunately, Winden cannot connect to the Least Authority servers. Please try again or let us know at [contact@winden.app](mailto:contact@winden.app) if the problem remains.
```

## How to reproduce

1. Open Destiny on Android and send a file (pic of 350k)
2. Open Firefox on Winden.app and enter the code to receive, then accept the file

Reproducibility: 100% (5/5)

## What browser(s) or client(s)  are you seeing the problem on?

- Sender: Destiny/1.0.1 Android/11
- Receiver: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0

## Relevant log output

Browser console says:
```
Error details:  failed to establish connection errors.tsx:17:2
```

**Comment by meejah** [comment]
I'm fairly sure that this is because the Destiny app will send a TCP relay hint (only) and Winden needs a WebSocket one.

I believe this is spec-only and not implemented anywhere (which .. could be made a lot more obvious in that repo's specification-code): https://github.com/magic-wormhole/magic-wormhole-protocols/blob/2349bf1cb8a78ee5e42de34aa10729419f3b4d02/transit.md#relay-v1 but that's the sort of thing we need. That is, a way to say "there a relay here and it can be reached at two different transports".

A temporary solution could be for Winden to automagically translate a tcp hint for the relay it knows about into a WebSocket one (since Winden is the only client that knows or cares about websocket relays).

**Comment by donpui** [comment]
> 

I can confirm, that Winden fails, because tries to connect to TCP relay hint. Destiny sends only TCP. Destiny should send at least both hints: TCP and Websocket.

Fallback option to WSS for Winden would be helpful in such cases.

Still not sure how we missed this scenario as we really tested interoperability with Destiny, Winden, Go CLI and MW python  versions and all variants with TCP/WSS.

**Comment by vu3rdd** [comment]
Posted a workaround draft PR. We should think of a proper fix. https://github.com/LeastAuthority/wormhole-william/pull/95

**Comment by donpui** [comment]
@btlogy this release: https://github.com/LeastAuthority/winden/releases/tag/0.5.3-beta fixed an issue. Please try and if still doesn't work, reopen.

**Comment by btlogy** [comment]
It seems to work now as expected indeed.
Thank you.
